const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Question = require("../models/Question");

dotenv.config();

// Sample questions for different exams and subjects
const SAMPLE_QUESTIONS = {
  NET: {
    maths: [
      { question: "What is the derivative of x³ + 2x² + 5x + 7?", optionA: "3x² + 4x + 5", optionB: "3x² + 2x + 5", optionC: "x² + 2x + 5", optionD: "3x³ + 4x² + 5x", correctAnswer: "A" },
      { question: "The value of ∫(2x + 3)dx from 0 to 1 is?", optionA: "3", optionB: "4", optionC: "5", optionD: "6", correctAnswer: "B" },
      { question: "What is the sum of angles in a triangle?", optionA: "90°", optionB: "180°", optionC: "270°", optionD: "360°", correctAnswer: "B" },
      { question: "If 2x + 5 = 13, what is the value of x?", optionA: "3", optionB: "4", optionC: "5", optionD: "6", correctAnswer: "B" },
      { question: "What is the square root of 144?", optionA: "10", optionB: "11", optionC: "12", optionD: "13", correctAnswer: "C" },
      { question: "The value of sin(90°) is?", optionA: "0", optionB: "0.5", optionC: "1", optionD: "√3/2", correctAnswer: "C" },
      { question: "What is 15% of 200?", optionA: "25", optionB: "30", optionC: "35", optionD: "40", correctAnswer: "B" },
      { question: "If a:b = 2:3 and b:c = 4:5, then a:c is?", optionA: "8:15", optionB: "2:5", optionC: "3:5", optionD: "4:5", correctAnswer: "A" },
      { question: "The HCF of 24 and 36 is?", optionA: "6", optionB: "8", optionC: "12", optionD: "24", correctAnswer: "C" },
      { question: "What is the value of log₁₀(1000)?", optionA: "1", optionB: "2", optionC: "3", optionD: "4", correctAnswer: "C" },
      { question: "The area of a circle with radius 7 is?", optionA: "44", optionB: "49π", optionC: "77", optionD: "154", correctAnswer: "D" },
      { question: "What is the LCM of 12 and 18?", optionA: "24", optionB: "30", optionC: "36", optionD: "42", correctAnswer: "C" },
      { question: "If x² - 5x + 6 = 0, then x is?", optionA: "2 or 3", optionB: "1 or 6", optionC: "2 or 4", optionD: "-2 or -3", correctAnswer: "A" },
      { question: "What is the value of (2³)²?", optionA: "32", optionB: "64", optionC: "128", optionD: "256", correctAnswer: "B" },
      { question: "The circumference of a circle with diameter 14 is?", optionA: "22", optionB: "44", optionC: "88", optionD: "196", correctAnswer: "B" },
      { question: "What is the average of 10, 20, 30, 40, 50?", optionA: "25", optionB: "30", optionC: "35", optionD: "40", correctAnswer: "B" },
      { question: "If a triangle has sides 3, 4, 5, it is?", optionA: "Acute", optionB: "Obtuse", optionC: "Right-angled", optionD: "Equilateral", correctAnswer: "C" },
      { question: "What is 0.5 × 0.2?", optionA: "0.01", optionB: "0.1", optionC: "0.001", optionD: "1", correctAnswer: "B" },
      { question: "The value of cos(0°) is?", optionA: "0", optionB: "0.5", optionC: "1", optionD: "√3/2", correctAnswer: "C" },
      { question: "What is the volume of a cube with side 2?", optionA: "4", optionB: "6", optionC: "8", optionD: "12", correctAnswer: "C" },
    ],
    reasoning: [
      { question: "Complete the series: 2, 4, 8, 16, 32, ?", optionA: "48", optionB: "56", optionC: "64", optionD: "72", correctAnswer: "C" },
      { question: "Which symbol should replace? 9 : 81 :: 7 : ?", optionA: "49", optionB: "63", optionC: "56", optionD: "70", correctAnswer: "A" },
      { question: "A is taller than B. C is shorter than D. A is shorter than C. Who is tallest?", optionA: "A", optionB: "B", optionC: "D", optionD: "Cannot be determined", correctAnswer: "C" },
      { question: "Find the odd one: 10, 25, 45, 70, 100", optionA: "25", optionB: "45", optionC: "70", optionD: "100", correctAnswer: "B" },
      { question: "If 1 = 5, 2 = 10, 3 = 15, then 4 = ?", optionA: "20", optionB: "25", optionC: "30", optionD: "35", correctAnswer: "A" },
      { question: "Complete: 1, 1, 2, 3, 5, 8, ?", optionA: "11", optionB: "12", optionC: "13", optionD: "14", correctAnswer: "C" },
      { question: "Next number: 2, 6, 12, 20, 30, ?", optionA: "40", optionB: "42", optionC: "44", optionD: "46", correctAnswer: "B" },
      { question: "Complete pattern: A1, C3, E5, G7, ?", optionA: "I9", optionB: "H8", optionC: "J10", optionD: "I8", correctAnswer: "A" },
      { question: "Which number replaces? 5, 10, ?, 40, 80", optionA: "15", optionB: "20", optionC: "25", optionD: "30", correctAnswer: "B" },
      { question: "Find missing: 1, 4, 10, 20, ?, 56", optionA: "30", optionB: "35", optionC: "38", optionD: "42", correctAnswer: "B" },
      { question: "Different from: 121, 144, 169, 196, 215", optionA: "121", optionB: "144", optionC: "169", optionD: "215", correctAnswer: "D" },
      { question: "Watch angle at 3:15?", optionA: "7.5°", optionB: "15°", optionC: "22.5°", optionD: "30°", correctAnswer: "A" },
      { question: "Which code NICE if SCIENCE = 2134567?", optionA: "4312", optionB: "6357", optionC: "4375", optionD: "7362", correctAnswer: "C" },
      { question: "Complete: Monday to Tuesday as Friday to ?", optionA: "Thursday", optionB: "Saturday", optionC: "Sunday", optionD: "Wednesday", correctAnswer: "B" },
      { question: "Find odd one: 2, 4, 8, 12, 16", optionA: "2", optionB: "8", optionC: "12", optionD: "16", correctAnswer: "C" },
      { question: "Next in sequence: Z, Y, X, W, ?", optionA: "U", optionB: "V", optionC: "W", optionD: "X", correctAnswer: "A" },
      { question: "Which comes next: 1, 4, 9, 16, ?", optionA: "20", optionB: "25", optionC: "30", optionD: "35", correctAnswer: "B" },
      { question: "Remaining shape in pattern?", optionA: "Circle", optionB: "Square", optionC: "Triangle", optionD: "Hexagon", correctAnswer: "A" },
      { question: "'Daughter of my father's sister' is my?", optionA: "Cousin", optionB: "Brother", optionC: "Uncle", optionD: "Father", correctAnswer: "A" },
      { question: "If all As are Bs and all Bs are Cs, then all As are Cs is?", optionA: "Induction", optionB: "Deduction", optionC: "Abduction", optionD: "Analogy", correctAnswer: "B" },
    ],
    computer: [
      { question: "What is RAM?", optionA: "Permanently stored memory", optionB: "Temporary memory for processor", optionC: "Memory for programs", optionD: "Secondary storage", correctAnswer: "B" },
      { question: "Closest to machine language?", optionA: "C++", optionB: "Java", optionC: "Assembly", optionD: "Python", correctAnswer: "C" },
      { question: "CPU stands for?", optionA: "Central Process Unit", optionB: "Central Processing Unit", optionC: "Central Processor Unit", optionD: "Contains Processing Unit", correctAnswer: "B" },
      { question: "Time complexity of binary search?", optionA: "O(n)", optionB: "O(n²)", optionC: "O(log n)", optionD: "O(1)", correctAnswer: "C" },
      { question: "Which uses LIFO?", optionA: "Queue", optionB: "Stack", optionC: "Array", optionD: "List", correctAnswer: "B" },
      { question: "Size of integer in C?", optionA: "1 byte", optionB: "2 bytes", optionC: "4 bytes", optionD: "8 bytes", correctAnswer: "C" },
      { question: "Best worst-case time complexity?", optionA: "Bubble sort", optionB: "Quick sort", optionC: "Merge sort", optionD: "Selection sort", correctAnswer: "C" },
      { question: "What is a pointer?", optionA: "Stores an address", optionB: "Returns integer", optionC: "Float data type", optionD: "Create arrays", correctAnswer: "A" },
      { question: "Constant keyword in Java?", optionA: "const", optionB: "constant", optionC: "final", optionD: "immutable", correctAnswer: "C" },
      { question: "HTML stands for?", optionA: "Hyper Text Markup Language", optionB: "High Text Markup Language", optionC: "Hyper Text Making Language", optionD: "Home Tool Markup Language", correctAnswer: "A" },
      { question: "Difference between array and pointer?", optionA: "No difference", optionB: "Array vs pointer", optionC: "Pointer vs array", optionD: "Both same", correctAnswer: "B" },
      { question: "Protocol for secure web?", optionA: "HTTP", optionB: "HTTPS", optionC: "FTP", optionD: "TCP", correctAnswer: "B" },
      { question: "Stack vs Queue difference?", optionA: "Stack FIFO Queue LIFO", optionB: "Stack LIFO Queue FIFO", optionC: "Same", optionD: "Random access", correctAnswer: "B" },
      { question: "API stands for?", optionA: "Application Programming Interface", optionB: "Automated Programming Interface", optionC: "Application Process Interface", optionD: "Application Protocol Interface", correctAnswer: "A" },
      { question: "NoSQL database?", optionA: "MySQL", optionB: "MongoDB", optionC: "PostgreSQL", optionD: "Oracle", correctAnswer: "B" },
      { question: "Virtual function purpose?", optionA: "Cannot be called", optionB: "Enable polymorphism", optionC: "Speed up program", optionD: "Save memory", correctAnswer: "B" },
      { question: "DRY stands for?", optionA: "Debug Run Yield", optionB: "Don't Repeat Yourself", optionC: "Data Receive Yield", optionD: "Direct Run Yield", correctAnswer: "B" },
      { question: "Best for dictionary?", optionA: "Array", optionB: "Stack", optionC: "Hash Table", optionD: "Linked List", correctAnswer: "C" },
      { question: "Abstract vs Interface?", optionA: "No difference", optionB: "Abstract has fields", optionC: "Interface has fields", optionD: "Interface faster", correctAnswer: "B" },
      { question: "2D array syntax in Java?", optionA: "int array[2][3]", optionB: "int[2][3] array", optionC: "int[][] array = new int[2][3]", optionD: "Both A and C", correctAnswer: "D" },
    ],
    english: [
      { question: "Synonym for benevolent?", optionA: "Cruel", optionB: "Kind", optionC: "Selfish", optionD: "Arrogant", correctAnswer: "B" },
      { question: "Correct spelling?", optionA: "Occassion", optionB: "Ocassion", optionC: "Occasion", optionD: "Ocassion", correctAnswer: "C" },
      { question: "Plural of child?", optionA: "Childs", optionB: "Childes", optionC: "Children", optionD: "Childrens", correctAnswer: "C" },
      { question: "Grammatically correct?", optionA: "She go to school", optionB: "She goes to school", optionC: "She gone to school", optionD: "She going to school", correctAnswer: "B" },
      { question: "Antonym of bright?", optionA: "Light", optionB: "Dark", optionC: "Clear", optionD: "Shiny", correctAnswer: "B" },
      { question: "Synonym for meticulous?", optionA: "Careless", optionB: "Careful", optionC: "Quick", optionD: "Slow", correctAnswer: "B" },
      { question: "Ubiquitous means?", optionA: "Very rare", optionB: "Present everywhere", optionC: "Extremely large", optionD: "Completely hidden", correctAnswer: "B" },
      { question: "Part of speech 'quickly'?", optionA: "Noun", optionB: "Verb", optionC: "Adjective", optionD: "Adverb", correctAnswer: "D" },
      { question: "Between you and?", optionA: "I", optionB: "Me", optionC: "Both correct", optionD: "Neither", correctAnswer: "B" },
      { question: "Homonym definition?", optionA: "Opposite meaning", optionB: "Similar meaning", optionC: "Sounds like another", optionD: "Rhymes with another", correctAnswer: "C" },
      { question: "Passive voice: 'Cat ate mouse'?", optionA: "Mouse eaten by cat", optionB: "Mouse ate cat", optionC: "Cat eating mouse", optionD: "Mouse eats cat", correctAnswer: "A" },
      { question: "Interested __ music?", optionA: "in", optionB: "on", optionC: "at", optionD: "with", correctAnswer: "A" },
      { question: "Error: 'Neither are here'?", optionA: "Are to is", optionB: "Neither to Either", optionC: "Boys to man", optionD: "No error", correctAnswer: "A" },
      { question: "Plural of thesis?", optionA: "Thesis", optionB: "Theses", optionC: "Theesis", optionD: "Thesis'", correctAnswer: "B" },
      { question: "Correctly punctuated?", optionA: "What wonderful day!", optionB: "What wonderful day,", optionC: "What wonderful day.", optionD: "What wonderful day:", correctAnswer: "A" },
      { question: "Nostalgic means?", optionA: "Feeling sick", optionB: "Sad about past", optionC: "Excited", optionD: "Angry", correctAnswer: "B" },
      { question: "Article: '___ apple'?", optionA: "The", optionB: "A", optionC: "An", optionD: "Any", correctAnswer: "C" },
      { question: "Superlative of good?", optionA: "Gooder", optionB: "Better", optionC: "Best", optionD: "Goodest", correctAnswer: "C" },
      { question: "Conjunction in 'I go but tired'?", optionA: "want", optionB: "but", optionC: "am", optionD: "tired", correctAnswer: "B" },
      { question: "Teacher was ___ behavior?", optionA: "amused", optionB: "confused", optionC: "appalled", optionD: "encouraged", correctAnswer: "C" },
    ],
    aptitude: [
      { question: "Man walks 4 km/h, covers 20 km in?", optionA: "4 hours", optionB: "5 hours", optionC: "6 hours", optionD: "8 hours", correctAnswer: "B" },
      { question: "Train 100m at 5 m/s, cross 150m platform in?", optionA: "30s", optionB: "40s", optionC: "50s", optionD: "60s", correctAnswer: "C" },
      { question: "3 men do work in 10 days, 5 men in?", optionA: "5 days", optionB: "6 days", optionC: "7 days", optionD: "8 days", correctAnswer: "B" },
      { question: "Sells at Rs. 100, 25% profit, cost price?", optionA: "Rs. 70", optionB: "Rs. 75", optionC: "Rs. 80", optionD: "Rs. 85", correctAnswer: "C" },
      { question: "A age : B age = 3:5, A = 15, B = ?", optionA: "20", optionB: "25", optionC: "30", optionD: "35", correctAnswer: "B" },
      { question: "Car 200 km in 4 hours, speed?", optionA: "40", optionB: "50", optionC: "60", optionD: "70", correctAnswer: "B" },
      { question: "CP 500, SP 600, profit %?", optionA: "10%", optionB: "15%", optionC: "20%", optionD: "25%", correctAnswer: "C" },
      { question: "Fill 6h, empty 8h, both open?", optionA: "20h", optionB: "22h", optionC: "24h", optionD: "26h", correctAnswer: "C" },
      { question: "60% of 150?", optionA: "80", optionB: "85", optionC: "90", optionD: "95", correctAnswer: "C" },
      { question: "If A:B = 2:3, B:C = 4:5, A:B:C?", optionA: "2:3:4", optionB: "8:12:15", optionC: "3:4:5", optionD: "4:6:8", correctAnswer: "B" },
      { question: "SI on 1000, 2 years, 5% p.a.?", optionA: "50", optionB: "100", optionC: "150", optionD: "200", correctAnswer: "B" },
      { question: "Number 5 times another, sum 60?", optionA: "8", optionB: "10", optionC: "12", optionD: "15", correctAnswer: "B" },
      { question: "Water 80%, sugar 20%, in 10L?", optionA: "1L", optionB: "2L", optionC: "3L", optionD: "4L", correctAnswer: "B" },
      { question: "Income +10%, new 5500, old?", optionA: "4000", optionB: "4500", optionC: "5000", optionD: "5500", correctAnswer: "C" },
      { question: "15 workers 10 days, 10 workers?", optionA: "12", optionB: "14", optionC: "15", optionD: "20", correctAnswer: "C" },
      { question: "A to B 60 km/h, B to A 40 km/h, avg?", optionA: "48", optionB: "50", optionC: "52", optionD: "55", correctAnswer: "A" },
      { question: "CI on 1000, 2 years, 10% p.a.?", optionA: "200", optionB: "210", optionC: "220", optionD: "230", correctAnswer: "C" },
      { question: "40% boys, 60% girls, 50 girls, boys?", optionA: "25", optionB: "30", optionC: "35", optionD: "40", correctAnswer: "A" },
      { question: "10% discount, original 500, new?", optionA: "400", optionB: "420", optionC: "450", optionD: "480", correctAnswer: "C" },
      { question: "2.5 hours at 80 km/h, distance?", optionA: "170", optionB: "180", optionC: "190", optionD: "200", correctAnswer: "D" },
    ],
  },
  SET: {
    maths: [
      { question: "7 × 8?", optionA: "54", optionB: "56", optionC: "58", optionD: "60", correctAnswer: "B" },
      { question: "√225?", optionA: "13", optionB: "14", optionC: "15", optionD: "16", correctAnswer: "C" },
      { question: "LCM of 6 and 9?", optionA: "18", optionB: "27", optionC: "36", optionD: "54", correctAnswer: "A" },
      { question: "50% of 80?", optionA: "30", optionB: "35", optionC: "40", optionD: "45", correctAnswer: "C" },
      { question: "HCF of 48 and 64?", optionA: "8", optionB: "12", optionC: "16", optionD: "32", correctAnswer: "C" },
      { question: "2³?", optionA: "6", optionB: "8", optionC: "9", optionD: "12", correctAnswer: "B" },
      { question: "π value?", optionA: "2.14", optionB: "3.14", optionC: "4.14", optionD: "5.14", correctAnswer: "B" },
      { question: "10% of 250?", optionA: "20", optionB: "22", optionC: "25", optionD: "30", correctAnswer: "C" },
      { question: "Rectangle l=5 b=3 area?", optionA: "8", optionB: "15", optionC: "20", optionD: "25", correctAnswer: "B" },
      { question: "3/4 as %?", optionA: "60%", optionB: "70%", optionC: "75%", optionD: "80%", correctAnswer: "C" },
      { question: "Square side 7 perimeter?", optionA: "28", optionB: "35", optionC: "49", optionD: "56", correctAnswer: "A" },
      { question: "12 ÷ 3/4?", optionA: "9", optionB: "12", optionC: "16", optionD: "18", correctAnswer: "C" },
      { question: "Mode of 1,2,2,3,3,3,4?", optionA: "1", optionB: "2", optionC: "3", optionD: "4", correctAnswer: "C" },
      { question: "|-5|?", optionA: "-5", optionB: "0", optionC: "5", optionD: "10", correctAnswer: "C" },
      { question: "0.5 + 0.25?", optionA: "0.50", optionB: "0.70", optionC: "0.75", optionD: "0.80", correctAnswer: "C" },
      { question: "6² - 5²?", optionA: "11", optionB: "12", optionC: "13", optionD: "14", correctAnswer: "A" },
      { question: "Median of 2,4,6,8,10?", optionA: "4", optionB: "6", optionC: "8", optionD: "10", correctAnswer: "B" },
      { question: "3 × 2 × 1?", optionA: "5", optionB: "6", optionC: "7", optionD: "8", correctAnswer: "B" },
      { question: "1/2 + 1/3?", optionA: "1/5", optionB: "2/5", optionC: "5/6", optionD: "3/5", correctAnswer: "C" },
      { question: "2.5 × 4?", optionA: "8", optionB: "9", optionC: "10", optionD: "11", correctAnswer: "C" },
    ],
    reasoning: [
      { question: "Series: 1,4,9,16,?", optionA: "20", optionB: "25", optionC: "30", optionD: "35", correctAnswer: "B" },
      { question: "Odd: 10,20,30,35,40?", optionA: "10", optionB: "20", optionC: "35", optionD: "40", correctAnswer: "C" },
      { question: "A > B, B > C, A > C based on?", optionA: "Logic", optionB: "Transitivity", optionC: "Equality", optionD: "Symmetry", correctAnswer: "B" },
      { question: "5,10,20,40,?", optionA: "60", optionB: "70", optionC: "80", optionD: "90", correctAnswer: "C" },
      { question: "1:2 :: 3:?", optionA: "4", optionB: "5", optionC: "6", optionD: "7", correctAnswer: "C" },
      { question: "Odd: 2,4,8,12,16", optionA: "2", optionB: "8", optionC: "12", optionD: "16", correctAnswer: "C" },
      { question: "If X=5, Y=10, Z=X+Y, Z=?", optionA: "10", optionB: "15", optionC: "20", optionD: "25", correctAnswer: "B" },
      { question: "Which wrong: 1<2, 3<1, 2>1, 3>2?", optionA: "1<2", optionB: "3<1", optionC: "2>1", optionD: "3>2", correctAnswer: "B" },
      { question: "A,C,E,G,?", optionA: "H", optionB: "I", optionC: "J", optionD: "K", correctAnswer: "B" },
      { question: "100,99,97,94,?", optionA: "90", optionB: "88", optionC: "85", optionD: "82", correctAnswer: "A" },
      { question: "2,3,5,7,11,?", optionA: "12", optionB: "13", optionC: "14", optionD: "15", correctAnswer: "B" },
      { question: "Z,Y,X,W,?", optionA: "U", optionB: "V", optionC: "W", optionD: "X", correctAnswer: "A" },
      { question: "Complete pattern: Monday,Wed,Fri,?", optionA: "Sunday", optionB: "Monday", optionC: "Tuesday", optionD: "Saturday", correctAnswer: "A" },
      { question: "A > B, B > C, C > D, shortest?", optionA: "A", optionB: "B", optionC: "C", optionD: "D", correctAnswer: "D" },
      { question: "12,24,36,48,61?", optionA: "12", optionB: "36", optionC: "48", optionD: "61", correctAnswer: "D" },
      { question: "If 1+1=2, 2+2=6, 3+3=12, 4+4=?", optionA: "16", optionB: "18", optionC: "20", optionD: "24", correctAnswer: "C" },
      { question: "BOOK=2415, COOL=?", optionA: "2441", optionB: "2245", optionC: "2251", optionD: "2541", correctAnswer: "B" },
      { question: "Odd: 121,144,169,196,215?", optionA: "121", optionB: "144", optionC: "169", optionD: "215", correctAnswer: "D" },
      { question: "Watch 3:15 angle?", optionA: "7.5°", optionB: "15°", optionC: "22.5°", optionD: "30°", correctAnswer: "A" },
      { question: "Next: 1,1,2,3,5,8,?", optionA: "11", optionB: "12", optionC: "13", optionD: "14", correctAnswer: "C" },
    ],
    computer: [
      { question: "HTML?", optionA: "Programming language", optionB: "Markup language", optionC: "Scripting language", optionD: "Query language", correctAnswer: "B" },
      { question: "Database?", optionA: "Python", optionB: "Java", optionC: "MySQL", optionD: "JavaScript", correctAnswer: "C" },
      { question: "URL?", optionA: "Universal Resource Locator", optionB: "Uniform Resource Locator", optionC: "Ultra Record Locator", optionD: "Unlimited Resource List", correctAnswer: "B" },
      { question: "Not programming?", optionA: "C++", optionB: "Java", optionC: "HTML", optionD: "Python", correctAnswer: "C" },
      { question: "OS main function?", optionA: "Run games", optionB: "Manage hardware", optionC: "Browse internet", optionD: "Create documents", correctAnswer: "B" },
      { question: "Web browser?", optionA: "Python", optionB: "Android", optionC: "Chrome", optionD: "Linux", correctAnswer: "C" },
      { question: "CPU?", optionA: "Central Processor Unit", optionB: "Central Processing Unit", optionC: "Computer Permanent Unit", optionD: "Central Program Unit", correctAnswer: "B" },
      { question: "Faster memory?", optionA: "RAM", optionB: "Hard Drive", optionC: "SSD", optionD: "Cache", correctAnswer: "D" },
      { question: "Byte size?", optionA: "8 bits", optionB: "16 bits", optionC: "32 bits", optionD: "64 bits", correctAnswer: "A" },
      { question: "Input device?", optionA: "Monitor", optionB: "Keyboard", optionC: "Speaker", optionD: "Printer", correctAnswer: "B" },
      { question: "GPU?", optionA: "Graphics Processing Unit", optionB: "General Purpose Unit", optionC: "Graphic Program Unit", optionD: "Global Processing Unit", correctAnswer: "A" },
      { question: "NoSQL?", optionA: "Oracle", optionB: "SQLite", optionC: "MongoDB", optionD: "PostgreSQL", correctAnswer: "C" },
      { question: "Variable?", optionA: "Fixed value", optionB: "Named storage", optionC: "Function", optionD: "Class", correctAnswer: "B" },
      { question: "Firewall?", optionA: "Speed internet", optionB: "Protect access", optionC: "Increase ram", optionD: "Clear cache", correctAnswer: "B" },
      { question: "Compiler?", optionA: "Python", optionB: "Java", optionC: "JavaScript", optionD: "Bash", correctAnswer: "B" },
      { question: "Cloud computing?", optionA: "Using clouds", optionB: "Remote servers", optionC: "Local computing", optionD: "Offline", correctAnswer: "B" },
      { question: "Version control?", optionA: "Docker", optionB: "Git", optionC: "Jenkins", optionD: "Maven", correctAnswer: "B" },
      { question: "OOP advantage?", optionA: "Faster", optionB: "Better organization", optionC: "Less memory", optionD: "Easier read", correctAnswer: "B" },
      { question: "Encryption?", optionA: "Unreadable data", optionB: "Compressing", optionC: "Deleting", optionD: "Copying", correctAnswer: "A" },
      { question: "Web development language?", optionA: "C", optionB: "Assembly", optionC: "JavaScript", optionD: "COBOL", correctAnswer: "C" },
    ],
    english: [
      { question: "Past of go?", optionA: "goes", optionB: "went", optionC: "going", optionD: "gone", correctAnswer: "B" },
      { question: "Noun?", optionA: "Run", optionB: "Fast", optionC: "Cat", optionD: "Quickly", correctAnswer: "C" },
      { question: "Plural mouse?", optionA: "mouses", optionB: "mice", optionC: "mices", optionD: "mousses", correctAnswer: "B" },
      { question: "Synonym happy?", optionA: "Sad", optionB: "Joyful", optionC: "Angry", optionD: "Tired", correctAnswer: "B" },
      { question: "Adjective?", optionA: "Describes nouns", optionB: "Describes verbs", optionC: "Replaces nouns", optionD: "Connects nouns", correctAnswer: "A" },
      { question: "I ___ store?", optionA: "go", optionB: "goes", optionC: "going", optionD: "gone", correctAnswer: "A" },
      { question: "Antonym big?", optionA: "Huge", optionB: "Small", optionC: "Large", optionD: "Great", correctAnswer: "B" },
      { question: "Verb?", optionA: "Blue", optionB: "Run", optionC: "Quick", optionD: "Beautiful", correctAnswer: "B" },
      { question: "Spelling?", optionA: "Recieve", optionB: "Receive", optionC: "Receve", optionD: "Recive", correctAnswer: "B" },
      { question: "Fragment?", optionA: "Complete", optionB: "No subject", optionC: "Long", optionD: "Easy", correctAnswer: "B" },
      { question: "Correct?", optionA: "Don't like", optionB: "Doesn't like", optionC: "Do not like", optionD: "Not like", correctAnswer: "B" },
      { question: "Pronoun?", optionA: "Type noun", optionB: "Replaces noun", optionC: "Describes", optionD: "Modifies", correctAnswer: "B" },
      { question: "Synonym lazy?", optionA: "Active", optionB: "Idle", optionC: "Busy", optionD: "Alert", correctAnswer: "B" },
      { question: "Past eat?", optionA: "eats", optionB: "eaten", optionC: "ate", optionD: "eating", correctAnswer: "C" },
      { question: "Adverb?", optionA: "Happy", optionB: "Happily", optionC: "Happiness", optionD: "Happier", correctAnswer: "B" },
      { question: "Plural box?", optionA: "boxs", optionB: "boxes", optionC: "boxe", optionD: "boces", correctAnswer: "B" },
      { question: "___ apple?", optionA: "A", optionB: "An", optionC: "The", optionD: "Some", correctAnswer: "B" },
      { question: "Opposite cold?", optionA: "Hot", optionB: "Warm", optionC: "Cool", optionD: "Freezing", correctAnswer: "A" },
      { question: "We ___ happy?", optionA: "is", optionB: "are", optionC: "be", optionD: "am", correctAnswer: "B" },
      { question: "Conjunction?", optionA: "Describing", optionB: "Connecting", optionC: "Name", optionD: "Action", correctAnswer: "B" },
    ],
    aptitude: [
      { question: "2 men 10 days, 1 man?", optionA: "5", optionB: "10", optionC: "20", optionD: "40", correctAnswer: "C" },
      { question: "Train 60 km/h, 2.5h?", optionA: "100", optionB: "120", optionC: "150", optionD: "180", correctAnswer: "C" },
      { question: "20% profit, CP 100, SP?", optionA: "80", optionB: "100", optionC: "120", optionD: "140", correctAnswer: "C" },
      { question: "30% of 90?", optionA: "20", optionB: "27", optionC: "30", optionD: "40", correctAnswer: "B" },
      { question: "1/3 work/day, full?", optionA: "1", optionB: "2", optionC: "3", optionD: "4", correctAnswer: "C" },
      { question: "SI 1000, 2y, 5%?", optionA: "50", optionB: "100", optionC: "150", optionD: "200", correctAnswer: "B" },
      { question: "SP 500, 25% profit, CP?", optionA: "300", optionB: "350", optionC: "400", optionD: "450", correctAnswer: "C" },
      { question: "A 5d, B 10d, together?", optionA: "3", optionB: "3.33", optionC: "4", optionD: "5", correctAnswer: "B" },
      { question: "3:5 as %?", optionA: "30%", optionB: "50%", optionC: "60%", optionD: "75%", correctAnswer: "C" },
      { question: "A:B = 3:4, total 70, A?", optionA: "30", optionB: "35", optionC: "40", optionD: "45", correctAnswer: "A" },
      { question: "D 100, S 50, T?", optionA: "1h", optionB: "1.5h", optionC: "2h", optionD: "3h", correctAnswer: "C" },
      { question: "10% off 500?", optionA: "400", optionB: "420", optionC: "450", optionD: "460", correctAnswer: "C" },
      { question: "Fill 4h, empty 6h, both?", optionA: "10h", optionB: "12h", optionC: "14h", optionD: "16h", correctAnswer: "B" },
      { question: "+10% from 100?", optionA: "105", optionB: "110", optionC: "115", optionD: "120", correctAnswer: "B" },
      { question: "A:B = 2:3, A 10, B?", optionA: "12", optionB: "15", optionC: "18", optionD: "20", correctAnswer: "B" },
      { question: "Avg 10,20,30?", optionA: "15", optionB: "20", optionC: "25", optionD: "30", correctAnswer: "B" },
      { question: "5% error, actual 100?", optionA: "95", optionB: "100", optionC: "105", optionD: "110", correctAnswer: "C" },
      { question: "A 5km/h, B 4km/h, 2h?", optionA: "9", optionB: "12", optionC: "15", optionD: "18", correctAnswer: "D" },
      { question: "Share 100, 1:4, first?", optionA: "10", optionB: "15", optionC: "20", optionD: "25", correctAnswer: "C" },
      { question: "CI 500, 2y, 10%?", optionA: "100", optionB: "105", optionC: "110", optionD: "115", correctAnswer: "B" },
    ],
  },
  NIMCET: {
    maths: [
      { question: "What is 8 × 9?", optionA: "70", optionB: "72", optionC: "74", optionD: "76", correctAnswer: "B" },
      { question: "√196 = ?", optionA: "12", optionB: "13", optionC: "14", optionD: "15", correctAnswer: "C" },
      { question: "20% of 150?", optionA: "25", optionB: "30", optionC: "35", optionD: "40", correctAnswer: "B" },
      { question: "LCM of 8 and 12?", optionA: "20", optionB: "24", optionC: "28", optionD: "32", correctAnswer: "B" },
      { question: "HCF of 36 and 48?", optionA: "6", optionB: "8", optionC: "12", optionD: "18", correctAnswer: "C" },
      { question: "3⁴?", optionA: "81", optionB: "82", optionC: "83", optionD: "84", correctAnswer: "A" },
      { question: "Circle circumference r=5?", optionA: "30", optionB: "31.4", optionC: "32.14", optionD: "33", correctAnswer: "B" },
      { question: "Area square side 8?", optionA: "62", optionB: "63", optionC: "64", optionD: "65", correctAnswer: "C" },
      { question: "1/3 + 1/4?", optionA: "1/7", optionB: "1/12", optionC: "7/12", optionD: "5/12", correctAnswer: "C" },
      { question: "Median of 3,5,7,9,11?", optionA: "5", optionB: "7", optionC: "9", optionD: "11", correctAnswer: "B" },
      { question: "sin 60°?", optionA: "1/2", optionB: "√3/2", optionC: "√2/2", optionD: "1", correctAnswer: "B" },
      { question: "cos 45°?", optionA: "1/2", optionB: "√3/2", optionC: "√2/2", optionD: "1", correctAnswer: "C" },
      { question: "tan 45°?", optionA: "0", optionB: "1", optionC: "√3", optionD: "∞", correctAnswer: "B" },
      { question: "log 100 base 10?", optionA: "1", optionB: "2", optionC: "3", optionD: "4", correctAnswer: "B" },
      { question: "Area triangle base 10, height 6?", optionA: "30", optionB: "35", optionC: "40", optionD: "60", correctAnswer: "A" },
      { question: "2⁵ × 2³?", optionA: "2⁸", optionB: "2⁷", optionC: "2⁶", optionD: "2⁴", correctAnswer: "A" },
      { question: "Average 5,10,15,20,25?", optionA: "13", optionB: "15", optionC: "17", optionD: "19", correctAnswer: "B" },
      { question: "5:7 as %?", optionA: "60%", optionB: "65%", optionC: "70%", optionD: "71.4%", correctAnswer: "D" },
      { question: "If x² = 64, x?", optionA: "6", optionB: "7", optionC: "8", optionD: "9", correctAnswer: "C" },
      { question: "Volume cube side 3?", optionA: "25", optionB: "26", optionC: "27", optionD: "28", correctAnswer: "C" },
    ],
    reasoning: [
      { question: "Series 2,4,7,11,?", optionA: "14", optionB: "15", optionC: "16", optionD: "17", correctAnswer: "C" },
      { question: "Odd 3,6,9,12,15", optionA: "3", optionB: "6", optionC: "9", optionD: "15", correctAnswer: "D" },
      { question: "A:B :: C:?", optionA: "D", optionB: "E", optionC: "F", optionD: "G", correctAnswer: "A" },
      { question: "Next Z,X,V,T,?", optionA: "R", optionB: "S", optionC: "U", optionD: "W", correctAnswer: "A" },
      { question: "If P > Q, Q > R, then?", optionA: "P > R", optionB: "R > P", optionC: "P = R", optionD: "Cannot say", correctAnswer: "A" },
      { question: "2,5,10,17,26,?", optionA: "35", optionB: "36", optionC: "37", optionD: "38", correctAnswer: "C" },
      { question: "DOG = 4,15,7, CAT = ?", optionA: "3,1,20", optionB: "2,3,4", optionC: "5,6,7", optionD: "8,9,10", correctAnswer: "A" },
      { question: "Which different 12,24,36,48,61", optionA: "12", optionB: "24", optionC: "36", optionD: "61", correctAnswer: "D" },
      { question: "3,8,18,38,78,?", optionA: "150", optionB: "152", optionC: "154", optionD: "158", correctAnswer: "D" },
      { question: "Ratio A:B:C = 2:3:4, total 90?", optionA: "20,30,40", optionB: "18,27,36", optionC: "22,33,44", optionD: "15,25,45", correctAnswer: "A" },
      { question: "Man walks 5km north, 3km east, then?", optionA: "8km", optionB: "√34km", optionC: "2km", optionD: "10km", correctAnswer: "B" },
      { question: "ABCD pattern, next?", optionA: "BCDE", optionB: "EFGH", optionC: "BCDF", optionD: "ADEF", correctAnswer: "A" },
      { question: "Age A 20, B 10, ratio after 10 years?", optionA: "2:1", optionB: "3:2", optionC: "3:1", optionD: "4:3", correctAnswer: "B" },
      { question: "Diamond ABCD, side x, perimeter?", optionA: "2x", optionB: "3x", optionC: "4x", optionD: "5x", correctAnswer: "C" },
      { question: "Odd one 121,144,169,196,224", optionA: "121", optionB: "144", optionC: "196", optionD: "224", correctAnswer: "D" },
      { question: "Code LOGIC is 12345, GOAL = ?", optionA: "9312", optionB: "9213", optionC: "9312", optionD: "9214", correctAnswer: "A" },
      { question: "Series 1,-1,2,-2,3,?", optionA: "-3", optionB: "3", optionC: "4", optionD: "-4", correctAnswer: "A" },
      { question: "Doctor is to Hospital as?", optionA: "Lawyer to Court", optionB: "Judge to Law", optionC: "Police to Crime", optionD: "Teacher to Subject", correctAnswer: "A" },
      { question: "If SQUARE = 6, CIRCLE = ?", optionA: "4", optionB: "5", optionC: "6", optionD: "7", correctAnswer: "C" },
      { question: "Next in spiral 1,3,5,7,9,11,?", optionA: "13", optionB: "14", optionC: "15", optionD: "16", correctAnswer: "A" },
    ],
    computer: [
      { question: "What is software?", optionA: "Physical equipment", optionB: "Programs and apps", optionC: "Hardware component", optionD: "Network cable", correctAnswer: "B" },
      { question: "Programming language type?", optionA: "High-level only", optionB: "Low-level only", optionC: "Both", optionD: "Neither", correctAnswer: "C" },
      { question: "Database table called?", optionA: "Record", optionB: "Field", optionC: "Row", optionD: "Column", correctAnswer: "C" },
      { question: "DBMS stands for?", optionA: "Database Memory Management", optionB: "Database Management System", optionC: "Data Backend Management", optionD: "Database Method System", correctAnswer: "B" },
      { question: "What is algorithm?", optionA: "Computer hardware", optionB: "Step-by-step procedure", optionC: "Database query", optionD: "Programming language", correctAnswer: "B" },
      { question: "Array elements accessed by?", optionA: "Name only", optionB: "Index", optionC: "Pointer", optionD: "Link", correctAnswer: "B" },
      { question: "Linked list node contains?", optionA: "Data and pointer", optionB: "Only data", optionC: "Only pointer", optionD: "Data and index", correctAnswer: "A" },
      { question: "Tree data structure?", optionA: "Linear", optionB: "Non-linear", optionC: "Both", optionD: "Neither", correctAnswer: "B" },
      { question: "Graph is collection of?", optionA: "Nodes only", optionB: "Edges only", optionC: "Nodes and edges", optionD: "Sets", correctAnswer: "C" },
      { question: "Sorting algorithm: merge?", optionA: "O(n)", optionB: "O(n²)", optionC: "O(n log n)", optionD: "O(log n)", correctAnswer: "C" },
      { question: "Search algorithm: linear?", optionA: "O(1)", optionB: "O(n)", optionC: "O(n²)", optionD: "O(log n)", correctAnswer: "B" },
      { question: "Stack is LIFO means?", optionA: "Last In First Out", optionB: "Linear In First Out", optionC: "Last In Fast Out", optionD: "List In First Out", correctAnswer: "A" },
      { question: "Queue is FIFO means?", optionA: "First In First Out", optionB: "Fast In Fast Out", optionC: "First Internal First Out", optionD: "Fast Internal First Out", correctAnswer: "A" },
      { question: "Binary search tree property?", optionA: "No order", optionB: "Left < Right", optionC: "Left > Right", optionD: "Random", correctAnswer: "B" },
      { question: "Hash table collision handled by?", optionA: "Deletion", optionB: "Chaining or probing", optionC: "Ignoring", optionD: "Rebuilding", correctAnswer: "B" },
      { question: "Shortest path algorithm?", optionA: "DFS", optionB: "BFS", optionC: "Dijkstra", optionD: "Preorder", correctAnswer: "C" },
      { question: "Tree traversal: inorder gives?", optionA: "Sorted order", optionB: "Random", optionC: "Reverse", optionD: "Level", correctAnswer: "A" },
      { question: "Recursion requires?", optionA: "Base case", optionB: "Recursive call", optionC: "Both", optionD: "Neither", correctAnswer: "C" },
      { question: "Dynamic programming solves?", optionA: "Simple prob", optionB: "Complex with overlap", optionC: "Linear only", optionD: "Sorting only", correctAnswer: "B" },
      { question: "Complexity best for 1M items?", optionA: "Bubble O(n²)", optionB: "Merge O(n log n)", optionC: "Insertion", optionD: "Selection", correctAnswer: "B" },
    ],
    english: [
      { question: "Synonym innovative?", optionA: "Old", optionB: "Creative", optionC: "Boring", optionD: "Simple", correctAnswer: "B" },
      { question: "Antonym transparent?", optionA: "Clear", optionB: "Opaque", optionC: "Bright", optionD: "Shiny", correctAnswer: "B" },
      { question: "Past tense \"write\"?", optionA: "writed", optionB: "wrote", optionC: "written", optionD: "writing", correctAnswer: "B" },
      { question: "Plural \"analysis\"?", optionA: "analysises", optionB: "analysis", optionC: "analyses", optionD: "analysys", correctAnswer: "C" },
      { question: "Active voice: 'Eat' ?", optionA: "Is eaten", optionB: "Eats", optionC: "Eaten", optionD: "Being eaten", correctAnswer: "B" },
      { question: "Imperative tense for?", optionA: "Questions", optionB: "Commands", optionC: "Statements", optionD: "Wishes", correctAnswer: "B" },
      { question: "Subordinate clause?", optionA: "Stands alone", optionB: "Depends on main", optionC: "Asks question", optionD: "Gives command", correctAnswer: "B" },
      { question: "Preposition in sentence?", optionA: "Replaces noun", optionB: "Shows relation", optionC: "Describes action", optionD: "Asks question", correctAnswer: "B" },
      { question: "Article 'the' is?", optionA: "Indefinite", optionB: "Definite", optionC: "Both", optionD: "Neither", correctAnswer: "B" },
      { question: "Idiom 'break ice'?", optionA: "Freeze ice", optionB: "Start conversation", optionC: "Break something", optionD: "Stop playing", correctAnswer: "B" },
      { question: "Metaphor is?", optionA: "Comparison with 'like'", optionB: "Direct comparison", optionC: "Question", optionD: "Command", correctAnswer: "B" },
      { question: "Simile uses?", optionA: "No comparison", optionB: "'Like' or 'as'", optionC: "Direct statement", optionD: "Replacement", correctAnswer: "B" },
      { question: "Oxymoron example?", optionA: "Good bad", optionB: "Bittersweet", optionC: "Real fake", optionD: "Happy sad", correctAnswer: "B" },
      { question: "Alliteration is?", optionA: "Word repetition", optionB: "Sound repetition", optionC: "Letter repeat", optionD: "Rhyming words", correctAnswer: "B" },
      { question: "Personification assigns?", optionA: "Human traits to objects", optionB: "Objects to humans", optionC: "Emotions", optionD: "Colors", correctAnswer: "A" },
      { question: "Which is correct?", optionA: "It's cat is black", optionB: "Its cat is black", optionC: "It is cat is black", optionD: "Its cat are black", correctAnswer: "B" },
      { question: "Who vs Whom?", optionA: "Same", optionB: "Who is object", optionC: "Whom is subject", optionD: "Whom is object", correctAnswer: "D" },
      { question: "Dangling modifier?", optionA: "Correct", optionB: "Unclear reference", optionC: "Proper", optionD: "Good", correctAnswer: "B" },
      { question: "Comma splice is error?", optionA: "Spacing", optionB: "Two sentences joined wrong", optionC: "Spelling", optionD: "Capitalization", correctAnswer: "B" },
      { question: "Subjunctive mood?", optionA: "Real condition", optionB: "Hypothetical", optionC: "Past", optionD: "Question", correctAnswer: "B" },
    ],
    aptitude: [
      { question: "6 men 15 days, 9 men?", optionA: "10 days", optionB: "12 days", optionC: "15 days", optionD: "18 days", correctAnswer: "A" },
      { question: "Bus 80 km/h, 5h, distance?", optionA: "350 km", optionB: "400 km", optionC: "450 km", optionD: "500 km", correctAnswer: "B" },
      { question: "CP 750, SP 900, profit%?", optionA: "15%", optionB: "18%", optionC: "20%", optionD: "25%", correctAnswer: "C" },
      { question: "25% of 320?", optionA: "70", optionB: "75", optionC: "80", optionD: "85", correctAnswer: "C" },
      { question: "1/5 work/day, full?", optionA: "3", optionB: "4", optionC: "5", optionD: "6", correctAnswer: "C" },
      { question: "SI 2000, 3y, 8%?", optionA: "480", optionB: "500", optionC: "550", optionD: "600", correctAnswer: "A" },
      { question: "SP 1200, loss 20%, CP?", optionA: "1200", optionB: "1400", optionC: "1500", optionD: "1600", correctAnswer: "C" },
      { question: "A 8 days, B 12 days, together?", optionA: "4.8 days", optionB: "5 days", optionC: "5.5 days", optionD: "6 days", correctAnswer: "A" },
      { question: "4:6 as %?", optionA: "60%", optionB: "65%", optionC: "66.66%", optionD: "70%", correctAnswer: "C" },
      { question: "A:B = 5:7, total 60?", optionA: "20", optionB: "25", optionC: "30", optionD: "35", correctAnswer: "B" },
      { question: "Speed 72 km/h = m/s?", optionA: "15", optionB: "18", optionC: "20", optionD: "25", correctAnswer: "C" },
      { question: "Markup 25%, CP 400?", optionA: "450", optionB: "500", optionC: "550", optionD: "600", correctAnswer: "B" },
      { question: "Fill 3h, empty 5h, both?", optionA: "6.5h", optionB: "7.5h", optionC: "8h", optionD: "8.5h", correctAnswer: "B" },
      { question: "20% increase from 500?", optionA: "550", optionB: "600", optionC: "650", optionD: "700", correctAnswer: "B" },
      { question: "Age ratio 3:4, diff 5, ages?", optionA: "15,20", optionB: "10,15", optionC: "8,13", optionD: "12,17", correctAnswer: "A" },
      { question: "Avg 12,15,18,21,24?", optionA: "16", optionB: "18", optionC: "20", optionD: "22", correctAnswer: "B" },
      { question: "10% discount on 1200?", optionA: "1000", optionB: "1050", optionC: "1080", optionD: "1100", correctAnswer: "C" },
      { question: "2 walk, rates 4, 5 km/h, 2h?", optionA: "12 km", optionB: "14 km", optionC: "16 km", optionD: "18 km", correctAnswer: "D" },
      { question: "Divide 144 in 1:3, parts?", optionA: "36,108", optionB: "24,120", optionC: "30,114", optionD: "32,112", correctAnswer: "A" },
      { question: "CI on 5000, 2y, 5%?", optionA: "500", optionB: "512.5", optionC: "550", optionD: "600", correctAnswer: "B" },
    ],
  },
};

// For exams not explicitly seeded above, fall back to the same question sets (to ensure the frontend always has questions)
SAMPLE_QUESTIONS.ASSISTANT_PROFESSOR = SAMPLE_QUESTIONS.NET;
SAMPLE_QUESTIONS.MPPSC = SAMPLE_QUESTIONS.NET;
SAMPLE_QUESTIONS.OTHER = SAMPLE_QUESTIONS.NET;

const run = async () => {
  try {
    const uri = process.env.MONGODB_URI || "mongodb://localhost:27017/quiz-app";
    await mongoose.connect(uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log("Connected to MongoDB for seeding");

    await Question.deleteMany({});
    console.log("Database cleared");

    const questionsToInsert = [];
    Object.entries(SAMPLE_QUESTIONS).forEach(([exam, subjects]) => {
      Object.entries(subjects).forEach(([subject, questions]) => {
        questions.forEach((q) => {
          questionsToInsert.push({
            ...q,
            exam,
            subject,
          });
        });
      });
    });

    await Question.insertMany(questionsToInsert);
    console.log(`✓ Seeded ${questionsToInsert.length} questions successfully`);
    process.exit(0);
  } catch (err) {
    console.error("Error seeding:", err);
    process.exit(1);
  }
};

run();

